default:
  options:
    hud_support: false
    video_threaded: true
    retroarch.menu_driver: rgui

amiga500:
  emulator: amiberry
  core:     A500
amiga1200:
  emulator: amiberry
  core:     A1200
amigacd32:
  emulator: amiberry
  core:     CD32
mastersystem:
  emulator: libretro
  core:     picodrive
megadrive:
  emulator: libretro
  core:     picodrive
snes:
  emulator: libretro
  core:     snes9x
c64:
  emulator: libretro
  core:     vice_x64
c128:
  emulator: libretro
  core:     vice_x128
c20:
  emulator: libretro
  core:     vice_xvic
pet:
  emulator: libretro
  core:     vice_xpet
cplus4:
  emulator: libretro
  core:     vice_xplus4
fmtowns:
  emulator: libretro
  core:     mame
atomiswave:
  emulator: flycast
  core:     flycast
dreamcast:
  emulator: flycast
  core:     flycast
naomi:
  emulator: flycast
  core:     flycast
naomi2:
  emulator: flycast
  core:     flycast
nds:
  emulator: drastic
  core:     drastic
fmtowns:
  emulator: libretro
  core:     mame
flash:
  emulator: lightspark
  core:     lightspark
psx:
  emulator: libretro
  core:     swanstation
  options:
    gpu_software: true # HW acceleration on swanstation is slow
scummvm:
  options:
    scumm_scale: 2
    scumm_stretch: pixel-perfect
