#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin

case "$1" in
  start)
    # Check if the brightness file exists and is readable
    if [ -r /userdata/system/.brightness ]; then
      # Read the brightness level from the file
      BRIGHTNESS=$(cat /userdata/system/.brightness)
      # Set the brightness level
      /usr/bin/rg35xx-plus-toolbox brightness -v "${BRIGHTNESS}"
    fi
    ;;
  stop)
    HDMISTATUS=$(cat /sys/devices/platform/soc/6000000.hdmi/extcon/hdmi/state)
    if [ "$HDMISTATUS" != "HDMI=1" ]; then
      BRIGHTNESS=$(/usr/bin/rg35xx-plus-toolbox brightness)
      echo $BRIGHTNESS > /userdata/system/.brightness
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/S27brightness {start} {stop}"
    exit 1
    ;;
esac

exit 0
